import "@/styles/globals.css";
import Head from "next/head";
import Layout from "@/component/Layout";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Gogrene-faithhouse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
